var isDone = true;
var notDone = false;
var dec = 6;
var hex = 0xf00d;
var binary = 10;
var octal = 16;
var myname = 'jesse';
var age = 27;
var sentence = "Hello, my name is " + myname + ", my age is " + age;
var listJs = [1, 2, 3];
var list = [1, 2, 3];
var listArray = [1, 2, 3];
var x;
x = ['hello', 10];
console.log(x[0].substr(1));
x[3] = 'world';
var Color;
(function (Color) {
    Color[Color["Red"] = 1] = "Red";
    Color[Color["Green"] = 2] = "Green";
    Color[Color["Blue"] = 3] = "Blue";
})(Color || (Color = {}));
;
var cNum = Color.Green;
var cstring = Color[2];
var notSure = 4;
notSure = "maybe a string instead";
notSure = false;
var listAny = [1, true, "free"];
var u = undefined;
var n = null;
var someValue = "this is a string";
var strLength = someValue.length;
var strLengthAs = someValue.length;
